import "./globals.css";
import "@fontsource/hammersmith-one";
import "@fontsource/fira-code";
import type { Metadata } from "next";

import { Providers } from "./providers";
import AuthCheck from "./components/authCheck";
import Sidebar from "./components/sidebar";

export const metadata: Metadata = {
  title: "Super - Billing | App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthCheck>
            <Sidebar>{children}</Sidebar>
          </AuthCheck>
        </Providers>
      </body>
    </html>
  );
}
